RefreshTokenDemo/Controllers/AuthenticationController.cs
using System;
using Microsoft.Owin.Security;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;
using Thinktecture.IdentityModel.Client;

namespace RefreshTokenDemo.Controllers
{
    public class AuthenticationController : Controller
    {
        public ActionResult AcrConnectLogin()
        {
            return new ChallengeResult("ACR ID", "/Home");
        }

        public async Task<ActionResult> AcrConnectCallback(string code)
        {
            var oidcClient = new OAuth2Client(new Uri(CustomAppSettings.TokenEndpointUrl, UriKind.Absolute), CustomAppSettings.ClientId, CustomAppSettings.ClientSecret, OAuth2Client.ClientAuthenticationStyle.PostValues);
            var response = await oidcClient.RequestAuthorizationCodeAsync(code, CustomAppSettings.AuthenticationRedirectUrl);

            SecureTokenStorage.RefreshToken = response.RefreshToken;

            return new RedirectResult("/");
        }
    }

    internal class ChallengeResult : HttpUnauthorizedResult
    {
        public ChallengeResult(string provider, string redirectUri)
        {
            LoginProvider = provider;
            RedirectUri = redirectUri;
        }

        public string LoginProvider { get; set; }
        public string RedirectUri { get; set; }

        public override void ExecuteResult(ControllerContext context)
        {
            var properties = new AuthenticationProperties { RedirectUri = RedirectUri };
            context.HttpContext.GetOwinContext().Authentication.Challenge(properties, LoginProvider);
        }
    }
}

RefreshTokenDemo/Controllers/ExternalServiceController.cs
using System;
using System.Net.Http;
using System.Net.Http.Headers;
using System.Threading.Tasks;
using System.Web.Mvc;
using Thinktecture.IdentityModel.Client;

namespace RefreshTokenDemo.Controllers
{
    public class ExternalServiceController : Controller
    {
        // GET: ExternalService
        public async Task<ActionResult> CallService()
        {
            await CallExternalServiceAsync(SecureTokenStorage.AccessToken);

            return Redirect("/");
        }

        public async Task<ActionResult> GetAccessToken()
        {
            var oidcClient = new OAuth2Client(new Uri(CustomAppSettings.TokenEndpointUrl, UriKind.Absolute), CustomAppSettings.ClientId, CustomAppSettings.ClientSecret, OAuth2Client.ClientAuthenticationStyle.PostValues);
            var response = await oidcClient.RequestRefreshTokenAsync(SecureTokenStorage.RefreshToken);

            SecureTokenStorage.RefreshToken = response.RefreshToken;
            SecureTokenStorage.AccessToken = response.AccessToken;

            return Redirect("/");
        }
        

        private static async Task CallExternalServiceAsync(string accessToken)
        {
            try
            {
                var client = new HttpClient();
                client.DefaultRequestHeaders.Authorization = new AuthenticationHeaderValue("Bearer", accessToken);
                var result = await client.GetStringAsync(CustomAppSettings.ExternalServiceUrl);
                SecureTokenStorage.ExternalServiceCallResult = result;
            }
            catch (Exception e)
            {
                SecureTokenStorage.ExternalServiceCallResult = e.Message;
            }
        }
    }
}

RefreshTokenDemo/Controllers/HomeController.cs
using System.Web.Mvc;

namespace RefreshTokenDemo.Controllers
{
    public class HomeController : Controller
    {
        // GET: Home
        public ActionResult Index()
        {
            return View();
        }
    }
}

RefreshTokenDemo/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Index";
}

<h2>Hello World!</h2>
@Html.ActionLink("ACR ID Login", "AcrConnectLogin", "Authentication")
<div>
    Refresh Token: @SecureTokenStorage.RefreshToken
</div>

@Html.ActionLink("Get Access Token", "GetAccessToken", "ExternalService")
<div>
    Access Token: @SecureTokenStorage.AccessToken
</div>


@Html.ActionLink("Call External Service", "CallService", "ExternalService")
<div>
    Result: @SecureTokenStorage.ExternalServiceCallResult
</div>

RefreshTokenDemo/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Refresh Token Demo</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Refresh Token Demo", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                </ul>
            </div>
        </div>
    </div>

    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Refresh Token Demo</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>